api/client.go
The pattern is described here https://sagikazarmark.hu/blog/functional-options-on-steroids/
One of its ability to extend API w/o breaking source compatibility.
```golang
api.NewClient(
api.Authenticator(...),
api.Endpoint("https://demo.privx.io"),
...
)
```
=> Use Functional Option pattern to config API client

api/client.go, api/client_test.go, api/rolestore/client.go, api/vault/vault.go, oauth/client.go
__WHAT__
* `NewClient` to `New`
* align structure of Client type between apis
=> rename api concepts

api/client.go, api/client_test.go, api/rolestore/client.go
Parse this object when constructing the Go error objects.
=> API endpoints return an error JSON object giving detail error information.

api/rolestore/client.go, api/vault/vault.go, oauth/authclient.go, oauth/authcode.go, restapi/client.go, restapi/client_test.go, restapi/opts.go, restapi/types.go
=> Adjust Interface of REST API calls

go.mod, go.sum, restapi/client.go, restapi/types.go
Add Delete(), and Fetch() binary content to REST API client
=> Enhance REST API client with ability to

README.md, oauth/auth.go, oauth/authtoken.go
* support explicit token auth if bearer token is provided
* support dynamic schema selection
=> Support flexible auth strategy that choose a right protocol

api/userstore/client.go, api/userstore/model.go
Added a new endpoint, /local-user-store/api/v1/users to the userstore.
Created a new User struct inside model.go.
=> added a new endpoint, /local-user-store/api/v1/users to the userstore

api/userstore/client.go
Added a new endpoint to userstore, get user by UID.
=> added a new endpoint to userstore, get user by uid

api/userstore/client.go
New endpoint added to the user store: DELETE `/local-user-store/api/v1/users/user_id`
=> added a new endpoint to userstore, delete local user

api/userstore/client.go
New endpoint added to the user store: PUT `/local-user-store/api/v1/users/user_id`
=> added a new endpoint to userstore, update local user

api/userstore/client.go
New endpoint added to the user store: PUT `/local-user-store/api/v1/users/user_id/password`
=> Add a new API endpoint, update local user password

api/userstore/client.go, api/userstore/model.go
New endpoint added to the user store: GET `/local-user-store/api/v1/users/tags`
=> add a new API endpoint, get local user tags

api/userstore/client.go
New endpoint added to the user store: PUT `/local-user-store/api/v1/trusted-clients/trusted_client_id`
=> add a new API endpoint, update trusted client

api/vault/model.go, api/vault/vault.go
New endpoint added to vault: POST `/vault/api/v1/search/secrets`
=> add a new API endpoint, search for secrets

api/hoststore/client.go, api/hoststore/model.go
- New endpoint added to host store: GET `/host-store/api/v1/hosts/{host_id}`
- Extended the Host struct in model
=> add a new API endpoint, get host

api/hoststore/client.go, api/hoststore/model.go
- New endpoint added to host store: GET `/host-store/api/v1/hosts`
- Added new Params struct to hoststore model
=> add a new API endpoint, get hosts

api/hoststore/client.go
New endpoint added to host store: POST `/host-store/api/v1/hosts/search`
=> add a new API endpoint, search hosts

api/hoststore/client.go
New endpoint added to host store: PUT `/host-store/api/v1/hosts/{host_id}`
=> add a new API endpoint, update host

api/hoststore/client.go
New endpoint added to host store: DELETE `/host-store/api/v1/hosts/{host_id}`
=> add a new API endpoint, delete host

api/hoststore/client.go
New endpoint added to host store: PUT `/host-store/api/v1/hosts/{host_id}/deployable`
=> Api endpoint/update deploy status

api/hoststore/client.go
New endpoint added to host store: POST `/host-store/api/v1/hosts/resolve`
=> add a new API endpoint, resolve host

api/rolestore/client.go, api/rolestore/model.go
New endpoint added to role store: GET `/role-store/api/v1/sources`
=> add a new API endpoint, get sources

api/rolestore/client.go
New endpoint added to host store: POST `/role-store/api/v1/sources`
=> feat(API): add a new API endpoint, create source

api/rolestore/client.go, api/rolestore/model.go
New endpoint added to host store: GET `/role-store/api/v1/sources/{source_id}`
=> feat(API): add a new API endpoint, get source

api/rolestore/client.go
New endpoint added to host store: DELETE `/role-store/api/v1/sources/{source_id}`
=> feat(API): add a new API endpoint, delete source

api/rolestore/client.go
New endpoint added to role store: PUT `/role-store/api/v1/sources/{source_id}`
=> feat(API): add a new API endpoint, update source

api/rolestore/client.go, api/rolestore/model.go
New endpoint added to role store: GET `/role-store/api/v1/awsroles`
=> feat(API): add a new API endpoint, get aws roles

api/rolestore/client.go
New endpoint added to role store: GET `/role-store/api/v1/awsroles/{awsrole_id}`
=> feat(API): add a new API endpoint, get aws role

api/rolestore/client.go
New endpoint added to role store: DELETE `/role-store/api/v1/awsroles/{awsrole_id}`
=> feat(API): add a new API endpoint, delete aws role

api/rolestore/client.go
New endpoint added to role store: GET `/role-store/api/v1/awsroles/{awsrole_id}/roles`
=> feat(API): add a new API endpoint, get aws role granting privx roles

api/rolestore/client.go, api/rolestore/model.go
- New endpoint added to role store: POST `/role-store/api/v1/roles/evaluate`
- Extended existing structs and added new ones to model.go
=> feat(API): add a new API endpoint, evaluate a new role

api/rolestore/client.go
New endpoint added to role store: DELETE `/role-store/api/v1/roles/{role_id}`
=> feat(API): add a new API endpoint to role-store, delete role

api/rolestore/client.go
New endpoint added to role store: PUT `/role-store/api/v1/roles/{role_id}`
=> feat(API): add a new API endpoint to role-store, update role

api/rolestore/client.go, api/rolestore/model.go
- New endpoint added to role store: GET `/role-store/api/v1/roles/{role_id}/principalkeys`
- New struct added to the role store model, `PrincipalKey`
=> feat(API): add a new API endpoint to role-store, get principal keys

api/rolestore/client.go
New endpoint added to role store: POST `/role-store/api/v1/roles/{role_id}/principalkeys/generate`
=> feat(API): add a new API endpoint to role-store, generate principal key

api/rolestore/client.go, api/rolestore/model.go
New endpoints added to role store:
- POST `/role-store/api/v1/roles/{role_id}/principalkeys/import`
- GET `/role-store/api/v1/roles/{role_id}/principalkeys/{key_id}`
- DELETE `/role-store/api/v1/roles/{role_id}/principalkeys/{key_id}`
New struct `PrivateKey` added to role store model
=> feat(API): add new API endpoints to role-store

api/rolestore/client.go
New endpoints added to role store:
- POST `/role-store/api/v1/users/mfa/enable` 
- POST `/role-store/api/v1/users/mfa/disable` 
- POST `/role-store/api/v1/users/mfa/reset`
=> feat(API): add new endpoints to role store

api/rolestore/client.go, api/rolestore/model.go
New endpoints added to role store:
- GET `/role-store/api/v1/roles/{role_id}/awstoken`
- GET `/role-store/api/v1/users/current`
- POST `/role-store/api/v1/users/search/external`
Included new struct to models `AWSToken` and extended the `Params` struct.
=> Api endpoint/role store

api/workflow/client.go, api/workflow/model.go
New endpoints:
- GET `/workflow-engine/api/v1/requests`
- POST `/workflow-engine/api/v1/requests`
- GET `/workflow-engine/api/v1/requests/{request_id}`
- DELETE `/workflow-engine/api/v1/requests/{request_id}`
- POST `/workflow-engine/api/v1/requests/{request_id}`
- POST `/workflow-engine/api/v1/requests/search`
- GET `/workflow-engine/api/v1/settings`
- PUT `/workflow-engine/api/v1/settings`
Model extended.
=> feat(API): add new endpoints to workflow

api/licensemanager/client.go
Removed named return values and naked returns according to the Jira ticket related to the license manager and golang's best practices.
=> fix(API): remove named return values and naked returns

api/rolestore/client.go, api/rolestore/model.go, restapi/client.go
Improved role store:
- Removed named return values and naked returns
- Restructured the function according to the api references
- Renamed functions and variables
- Changed the types of the query params and added a bool type check to the function `encodeURL` inside the rest api client file
=> fix(API): restruct functions, remove named return values, naked returns

api/workflow/client.go, api/workflow/model.go
- Restructured functions according to the api reference layout 
- Removed named return values and naked returns 
- Renamed variables
- Added a new endpoint POST `/workflow-engine/api/v1/testsmtp`
=> fix(API): restruct functions, add endpoint

api/connectionmanager/client.go
- Renamed functions
- Added a query parameter to `SearchConnections`
=> fix(API): rename functions

api/monitor/client.go, api/monitor/model.go
- Restructured functions according to the api references
- Fixed the fuzzycount display
- Renamed functions and variables
- Changed offset and limit to type int
- Removed named return values and naked returns
=> Api endpoint/monitor service

api/trailindex/client.go, api/trailindex/model.go
-  Restructured functions according to the api references
-  Changed offset and limit to type int
-  Removed named return values and naked returns
=> fix(API): remove named return values, restructured functions

api/workflow/client.go, api/workflow/model.go
- Renamed functions
- Removed json.RawMessage returns
=> fix(API): rename functions, remove json rawmessage returns

api/hoststore/client.go, api/hoststore/model.go
Refactored the client and model to be aligned to the latest changes.
- renamed functions and variables
- changed variable types
- functions are structured according to the api reference 
- removed named return values and naked returns
=> fix(API): refactor hoststore client and model

api/userstore/client.go, api/userstore/model.go
- renamed functions and variables
- changed variable types
- functions are structured according to the api reference
- removed named return values and naked returns
=> fix(API): refactor userstore client and model

api/vault/model.go, api/vault/vault.go
- renamed functions and variables
- changed variable types
- functions are structured according to the api reference
- removed named return values and naked returns
=> fix(API): refactor vault client and model

api/userstore/model.go
Model was incomplete, which resulted in an error while creating a trusted client.
=> fix(API): fix incomplete model

README.md
Update README file to clarify and explain the steps required to setup the client connector to connect with privx backend instance, existing workflow steps modified to  modular working functions example that can be plugged in to readily create the client connector for the SDK.
**Purpose of making these changes**
Making these set of changes to README, because as a first-time contributor to this repo, I had a bit of a problem catching the details in the exisitng README file. Particularly, the explanation about authorizing and setting up the client/connector was not very clear to me.
That appealed me into modifying the README file a little bit, which probably makes it a little bit easier to understand.
=> Update README file to clarify the step required to setup the API client/connector

api/hoststore/model.go, api/licensemanager/model.go
Max_users is added to the license object.
Objects in host store are modified.
=> Changes object definition for license manager and host store

api/userstore/model.go
Add missing trustedclient/extender attributes
=> api: trustedclient: add attributes

api/authorizer/client.go, api/connectionmanager/client.go, api/connectionmanager/model.go
I added the connection tags APIs, and fixed the missing "fuzzycount" problem for the other connection APIs.
I added the access group CA key APIs
=> ADD connection tag and access group CA key APIs

api/auth/client.go, api/auth/model.go, api/licensemanager/client.go, api/licensemanager/model.go
- Register/Unregister to/from MobileGW
- List paired devices of a user
- Unpair a user's device
=> added mobilegw endpoints

api/secretsmanager/model.go, api/userstore/model.go
- Add Attributes to LocalUser model
- Add DisableRDPCertAuth to ManagedAccount and related models
=> PrivX 36: models changes as a result of windows SID feature

.github/workflows/go.yml, api/secretsmanager/model.go, api/userstore/model.go
- Adding support for PrivX 36.0
- Fix Github workflow
=> Support PrivX 36.0
