.github/workflows/go.yml, api/client.go, api/client_test.go, api/rolestore/client.go, api/vault/vault.go, oauth/client.go
__WHAT__
1. Interfaces
SDK defines interface for core concepts 
* `oauth.Provider`
* `api.Connetor`
Interfaces helps to mock and test SDK implementation
2. Declarative HTTP I/O
The proposal is inspired by my declarative HTTP libraries
```
api.Connector -[ creates ]-> *CURL
CURL implements
func (curl *CURL) Send(data interface{}) *CURL
func (curl *CURL) Recv(data interface{}) error
func (curl *CURL) RecvStatus() error
```
Example of usage
```
err = vault.api.
Get("/vault/api/v1/secrets/%s", url.PathEscape(name)).
Recv(&bag)
```
3. Unit testing for client 
__NOTE__
* api.Client requires a lot of refactoring but it happens in future PR. We need to unlock boilerplate less api development asap.
* We need to agree about type-safe approach across api methods but it happens in later as well
=> Declarative approach to implement API calls

api/auth/client.go, api/auth/model.go
Use pointers to return results of API operation. The pointers makes return values look-like either data type.
```
// good, returned values are pointers
func A() (*User, error)
func B() ([]User, error)
// bad
func A() (User, error)
func B() ([]*User, error)
```
=> Improve semantic of API's return values

api/userstore/client.go
New endpoint added to the user store: GET `/local-user-store/api/v1/extender-clients`
=> add a new API endpoint, get extender clients

api/vault/model.go, api/vault/vault.go
New endpoint added to vault: GET `/vault/api/v1/secrets`
I also renamed the existing `Get` function to `Secret`, according to go's best practice as discussed in a previus pull request.
=> add a new API endpoint, get secrets from vault

api/vault/vault.go
New endpoint added to vault: GET `/vault/api/v1/metadata/secrets/{name}`
=> add a new API endpoint, get secret metadata

api/hoststore/client.go, api/hoststore/model.go
New endpoint added to host store: GET `/host-store/api/v1/hosts/tags`
=> add a new API endpoint, get host tags

api/hoststore/client.go, api/hoststore/model.go
- New endpoint added to host store: GET `/host-store/api/v1/settings/default_service_options`
- Added a new struct `DefaultServiceOptions` to the host store model
=> add a new API endpoint, get default service options

api/rolestore/client.go
New endpoints added to role store:
- POST `/role-store/api/v1/sources/refresh`
- GET `/role-store/api/v1/users/current/awsroles`
- GET `/role-store/api/v1/users/{user_id}/resolve`
=> feat(API): add new endpoints to role store

api/licensemanager/client.go, api/licensemanager/model.go
Included a new client to the SDK: `licensemanager` 
Added new endpoints to licensemanager:
- GET `/license-manager/api/v1/license`
- POST `/license-manager/api/v1/license/optin`
- POST `/license-manager/api/v1/license`
=> feat(API): add new client licensemanager to SDK and endpoints

api/licensemanager/client.go, restapi/client.go, restapi/types.go
Added new endpoints:
- POST `/license-manager/api/v1/license/refresh`
- POST `/license-manager/api/v1/license/deactivate`
Added a new rest api and type to the CURL interface in order to post content without an entity body
=> feat(API): add new endpoints to license manager, add new rest api

api/settings/client.go, api/settings/model.go
Add settings service client and model to SDK
Add new endpoints to settings service:
- GET `/settings/api/v1/settings/{scope}`
- PUT `/settings/api/v1/settings/{scope}`
- GET `/settings/api/v1/settings/{scope}/{section}`
- PUT `/settings/api/v1/settings/{scope}/{section}`
- GET `/settings/api/v1/schema/{scope}`
- GET `/settings/api/v1/schema/{scope}/{section}`
=> feat(API): add settings service to sdk and new endpoints

api/monitor/client.go, api/monitor/model.go
Added a new client, monitor, too SDK.
Added new endpoints to monitor service:
- GET `/monitor-service/api/v1/components`
- GET `/monitor-service/api/v1/components/{hostname}`
- POST `/monitor-service/api/v1/auditevents/search`
- GET `/monitor-service/api/v1/auditevents`
- GET `/monitor-service/api/v1/auditevents/codes`
- GET `/monitor-service/api/v1/instance/status`
- POST `/monitor-service/api/v1/instance/exit`
=> feat(API): add monitor client to SDK and new endpoints

api/trailindex/client.go, api/trailindex/model.go
Added new client and model to SDK, trail-index.
Added new endpoints to trail-index service.
- GET `/trail-index/api/v1/index/{connection_id}/status`
- POST `/trail-index/api/v1/index/status`
- POST `/trail-index/api/v1/index/start`
- POST `/trail-index/api/v1/index/search`
=> feat(API): add new client and endpoits  to SDK, trail index

api/workflow/client.go, api/workflow/model.go
Added a new client and model, workflow-engine to the SDK.
New added endpoints:
- GET `/workflow-engine/api/v1/workflows`
- POST `/workflow-engine/api/v1/workflows`
- GET `/workflow-engine/api/v1/workflows/{workflow_id}`
- DELETE `workflow-engine/api/v1/workflows/{workflow_id}`
- PUT `workflow-engine/api/v1/workflows/{workflow_id}`
=> feat(API): add new client, workflow engine, and endpoints to sdk

api/connectionmanager/client.go, api/connectionmanager/model.go, go.mod, go.sum, restapi/client.go, restapi/types.go
New client and model, connection-manager, added to the SDK.
Created a new type `Download` for the SDK in order to download a file via endpoint and save it to OS. 
New endpoints added to connection-manager:
- GET `/connection-manager/api/v1/connections`
- POST `/connection-manager/api/v1/connections/search`
- GET `/connection-manager/api/v1/connections/{connection_id}`
- POST `/connection-manager/api/v1/connections/{connection_id}/channel/{channel_id}/file/{file_id}`
- GET `/connection-manager/api/v1/connections/{connection_id}/channel/{channel_id}/file/{file_id}/{session_id}`
=> feat(API): add new client to sdk, add new restapi and type

api/connectionmanager/client.go
Add new endpoints to connection manager:
- POST `/connection-manager/api/v1/connections/{connection_id}/channel/{channel_id}/log`
- GET `/connection-manager/api/v1/connections/{connection_id}/channel/{channel_id}/log/{session_id}`
- GET `/connection-manager/api/v1/connections/{connection_id}/access_roles`
- POST `/connection-manager/api/v1/connections/{connection_id}/access_roles/{role_id}`
- DELETE `/connection-manager/api/v1/connections/{connection_id}/access_roles/{role_id}`
- DELETE `/connection-manager/api/v1/connections/access_roles/{role_id}`
- POST `/connection-manager/api/v1/terminate/connection/{connection_id}`
- POST `/connection-manager/api/v1/terminate/host/{host_id}`
- POST `/connection-manager/api/v1/terminate/user/{user_id}`
=> feat(API): add endpoints to connection manager

api/settings/client.go
- Restructured functions according to the api reference doc layout.
- Removed named return values and naked returns.
- Renamed variables.
=> fix(API): restruct functions, remove named return values, naked returns

api/rolestore/client.go, api/rolestore/model.go
- Renamed functions
- Change a single string parameter in `UpdateAWSRoleLink`, to a slice according to the api reference.
=> fix(API): rename functions, add new param to function

api/authorizer/client.go, api/authorizer/model.go
Added new endpoints to authorizer client:
- GET `/authorizer/api/v1/extender/cas`
- GET `/authorizer/api/v1/extender/cas/{id}`
- GET `/authorizer/api/v1/extender/cas/{id}/crl`
- POST `/authorizer/api/v1/extender/conf/{trusted_client_id}`
- GET `/authorizer/api/v1/extender/conf/{trusted_client_id}/{session_id}`
- POST `/authorizer/api/v1/trusted-clients/health-check`
- GET `/authorizer/api/v1/version.js`
- POST `/authorizer/api/v1/deploy/{trusted_client_id}`
- GET `/authorizer/api/v1/deploy/{trusted_client_id}/{session_id}`
- GET `/authorizer/api/v1/deploy/principals_command.sh`
=> Api endpoint/authorizer

api/authorizer/client.go, api/authorizer/model.go
Removed `TrustedClientHealthCheck `.
Added new final endpoints:
- POST `/authorizer/api/v1/carrier/conf/{trusted_client_id}`
- GET `/authorizer/api/v1/carrier/conf/{trusted_client_id}/{session_id}`
- POST `/authorizer/api/v1/icap/conf/{trusted_client_id}`
- GET `/authorizer/api/v1/icap/conf/{trusted_client_id}/{session_id}`
- GET `/authorizer/api/v1/cert/templates`
- GET `/authorizer/api/v1/ssl-trust-anchor`
- GET `/authorizer/api/v1/extender-trust-anchor`
- GET `/authorizer/api/v1/accessgroups`
- POST `/authorizer/api/v1/accessgroups`
- POST `/authorizer/api/v1/accessgroups/search`
- GET `/authorizer/api/v1/accessgroups/{id}`
- PUT `/authorizer/api/v1/accessgroups/{id}`
- POST `/authorizer/api/v1/cert/search`
=> feat(API): add new endpoints, remove health check endpoint

api/authorizer/client.go
Added missing endpoints to the authorizer client:
- GET `/authorizer/api/v1/icap/cas`
- GET `/authorizer/api/v1/icap/cas/{id}`
- GET `/authorizer/api/v1/icap/cas/{id}/crl`
- DELETE `/authorizer/api/v1/accessgroups/{id}`
=> fix(API): add missing endpoints

api/auth/client.go, api/auth/model.go
Added new client, auth, to sdk.
Added a new endpoint to auth:
- GET `/auth/api/v1/status`
=> feat(API): add auth client to sdk

api/rolestore/client.go
=> adding the missing query parameters for SearchUsers()

api/connectionmanager/client.go, api/connectionmanager/model.go
These were missed out in earlier commit as the API reference [page](https://privx.docs.ssh.com/reference/ueba-status) for this was empty.
=> Add ueba status and internal status endpoints to GO SDK

oauth/authclient.go, oauth/authtoken.go, oauth/opts.go, oauth/types.go, restapi/client.go, restapi/types.go
Adds an oauth option UseCookies() to enable using a cookie for subsequent requests. Cookies are not currently supported for the explicit auth method.
This is for feature parity with the Python SDK.
=> Cookie support

api/rolestore/client.go
Adding pagination parameters to the `GetRoleMembers()` method.
[The PrivX API docs](https://privx.docs.ssh.com/api/role-store/role#get--role-store-api-v1-roles-%7Brole-id%7D-members) include pagination parameters but the method does not.
Copying the pattern from the `SearchUsers()` method.
=> Add pagination parameters to `GetRoleMembers()`
